# Configure the Terraform providers
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0" # Specify a compatible version for the AWS provider
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0" # Specify a compatible version for the TLS provider
    }
  }
}

# Configure the AWS provider with the specified region
provider "aws" {
  region = "us-east-1" # Region obtained from the JSON configuration
}

# Generate a new SSH private key for administrative access to the VM
# This key will be used to establish SSH connections.
resource "tls_private_key" "admin_ssh" {
  algorithm = "RSA" # Using RSA algorithm for the key
  rsa_bits  = 4096  # Setting the key strength to 4096 bits
  # CRITICAL: The 'tls_private_key' resource does NOT support a 'comment' argument.
}

# Create an AWS Key Pair using the public key generated by the 'tls_private_key' resource.
# This key pair will be associated with the EC2 instance.
resource "aws_key_pair" "admin_key" {
  key_name   = "test-ip-2-admin-key" # A unique name for the key pair in AWS
  public_key = tls_private_key.admin_ssh.public_key_openssh # Use the OpenSSH format of the public key
  tags = {
    Name = "test-ip-2-admin-key"
  }
}

# Data source to find the custom Amazon Machine Image (AMI) ID.
# This searches for an AMI owned by the current account, matching the specified name.
data "aws_ami" "this_ami" {
  most_recent = true     # Retrieve the most recent AMI if multiple match
  owners      = ["self"] # Filter for AMIs owned by the current AWS account

  filter {
    name   = "name"
    values = ["amazon-linux-2023-19199576595"] # CRITICAL: Actual Cloud Image Name provided in instructions
  }
  # CRITICAL: Do NOT use a top-level 'name' argument on the data source.
}

# Deploy the virtual machine (EC2 instance) on AWS.
resource "aws_instance" "this_vm" {
  # CRITICAL: The primary compute resource MUST be named "this_vm".
  ami           = data.aws_ami.this_ami.id # Use the ID retrieved from the data source for the custom image
  instance_type = "t3.micro"               # Instance type obtained from the JSON configuration
  key_name      = aws_key_pair.admin_key.key_name # Attach the generated SSH key pair for access

  # User data script from JSON. It's commented out as per the JSON's instruction.
  # user_data = "#!/bin/bash\n# User data scripts are not yet supported for direct deployment.\n"

  tags = {
    Name = "test-ip-2" # Instance name obtained from the JSON configuration
  }
}

# CRITICAL: Output block named "private_ip" that exposes the private IP address of the VM.
output "private_ip" {
  description = "The private IP address of the deployed virtual machine."
  value       = aws_instance.this_vm.private_ip
}

# CRITICAL: Output block named "private_ssh_key" that exposes the generated private key.
# This output is marked as sensitive to prevent it from being displayed in plaintext in logs.
output "private_ssh_key" {
  value     = tls_private_key.admin_ssh.private_key_pem
  sensitive = true
}