packer {
  required_plugins {
    amazon = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

variable "build_id" {
  type    = string
  default = "local"
}

variable "platform" {
  type    = string
  default = "unknown"
}

variable "vm_size" {
  type    = string
  default = "t3.medium"
}

source "amazon-ebs" "autogenerated" {
  ami_name      = "amazon-linux-2023-${var.build_id}"
  instance_type = var.vm_size
  region        = "us-east-1"
  
  source_ami_filter {
    filters = {
      name                = "al2023-ami-2023.*-x86_64"
      virtualization-type = "hvm"
    }
    owners      = ["137112412989"]
    most_recent = true
  }
  ssh_username  = "ec2-user"
  
  
  
  

  tags = {
    Name      = "amazon-linux-2023"
    OS_Version = "amazon-linux-2023"
    CreatedBy = "Packer"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated"]
}