packer {
  required_plugins {
    azure = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/azure"
    }
  }
}



variable "build_id" {
  type    = string
  default = "local"
}

variable "platform" {
  type    = string
  default = "unknown"
}

variable "managed_image_rg" {
  type        = string
  description = "The destination resource group for the managed image."
}

variable "build_resource_group_name" {
  type        = string
  description = "The name of an existing resource group to use for temporary build resources."
}

variable "vm_size" {
  type    = string
  default = "Standard_D2s_v3"
}

source "azure-arm" "autogenerated" {
  use_azure_cli_auth = true
  image_offer     = "0001-com-ubuntu-server-jammy"
  image_publisher = "canonical"
  image_sku       = "22_04-lts-gen2"
  os_type         = "Linux"
  
  managed_image_name                       = "ubuntu-22-04-${var.build_id}"
  managed_image_resource_group_name        = var.managed_image_rg
  
  build_resource_group_name                = var.build_resource_group_name
  
  vm_size         = var.vm_size
  
  
  
}

build {
  sources = ["source.azure-arm.autogenerated"]
}