packer {
  required_plugins {
    amazon = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

variable "build_id" {
  type    = string
  default = "local"
}

variable "platform" {
  type    = string
  default = "unknown"
}

variable "vm_size" {
  type    = string
  default = "t3.medium"
}

source "amazon-ebs" "autogenerated" {
  ami_name      = "windows-11-${var.build_id}"
  instance_type = var.vm_size
  region        = "us-east-1"
  
  source_ami_filter {
    filters = {
      name                = "Windows-11-English-*-Pro-*-*"
      virtualization-type = "hvm"
    }
    owners      = ["801119661308"]
    most_recent = true
  }
  ssh_username  = "Administrator"
  communicator   = "winrm"
  winrm_username = "Administrator"
  winrm_use_ssl  = true
  winrm_insecure = true

  tags = {
    Name      = "windows-11"
    OS_Version = "windows-11"
    CreatedBy = "Packer"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated"]
}