packer {
  required_plugins {
    azure = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/azure"
    }
  }
}



variable "build_id" {
  type    = string
  default = "local"
}

variable "platform" {
  type    = string
  default = "unknown"
}

variable "managed_image_rg" {
  type        = string
  description = "The destination resource group for the managed image."
}

variable "vm_size" {
  type    = string
  default = "Standard_D2s_v3"
}

source "azure-arm" "autogenerated" {
  use_azure_cli_auth = true
  image_offer     = "WindowsServer"
  image_publisher = "MicrosoftWindowsServer"
  image_sku       = "2019-datacenter"
  os_type         = "Windows"
  
  managed_image_name                       = "windows-2019-${var.build_id}"
  managed_image_resource_group_name        = var.managed_image_rg
  
  vm_size         = var.vm_size
  communicator     = "winrm"
  winrm_username     = "packer"
  winrm_use_ssl      = false
  winrm_timeout      = "15m"

  # This empty plan_info block is a workaround to force a VM provisioning
  # method that does not require creating a temporary Key Vault, which can
  # fail on subscriptions where the Key Vault provider is not registered.
  plan_info {
  }
}

build {
  sources = ["source.azure-arm.autogenerated"]
}