packer {
  required_plugins {
    amazon = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

variable "build_id" {
  type    = string
  default = "local"
}

variable "platform" {
  type    = string
  default = "unknown"
}

variable "vm_size" {
  type    = string
  default = "t3.medium"
}

source "amazon-ebs" "autogenerated" {
  ami_name      = "windows-2022-${var.build_id}"
  instance_type = var.vm_size
  region        = "us-east-1"
  
  source_ami_filter {
    filters = {
      name                = "Windows_Server-2022-English-Full-Base-*"
      virtualization-type = "hvm"
    }
    owners      = ["801119661308"]
    most_recent = true
  }
  ssh_username  = "Administrator"
  communicator   = "winrm"
  winrm_username = "Administrator"
  winrm_use_ssl  = true
  winrm_insecure = true
  associate_public_ip_address = true
  temporary_security_group_source_cidrs = ["0.0.0.0/0"]
  winrm_timeout = "15m"

  tags = {
    Name      = "windows-2022"
    OS_Version = "windows-2022"
    CreatedBy = "Packer"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated"]
}