packer {
  required_plugins {
    azure = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/azure"
    }
  }
}



variable "build_id" {
  type    = string
  default = "local"
}

variable "platform" {
  type    = string
  default = "unknown"
}

variable "managed_image_rg" {
  type        = string
  description = "The destination resource group for the managed image."
}

variable "vm_size" {
  type    = string
  # Use a smaller, 1-core VM by default to reduce costs and stay within
  # common subscription quotas for regional vCPUs.
  default = "Standard_B1s"
}

source "azure-arm" "autogenerated" {
  use_azure_cli_auth = true
  # Use the same resource group for the temporary build resources
  # as for the final managed image. This avoids needing permissions
  # to create/delete resource groups, which caused the AuthorizationFailed error.
  build_resource_group_name = var.managed_image_rg

  image_offer                              = "WindowsServer"
  image_publisher                          = "MicrosoftWindowsServer"
  image_sku                                = "2019-datacenter"
  os_type                                  = "Windows"
  
  managed_image_name                       = "windows-2019-${var.build_id}"
  managed_image_resource_group_name        = var.managed_image_rg
  
  vm_size         = var.vm_size
  communicator     = "winrm"
  winrm_username     = "packer"
  winrm_use_ssl      = true
  winrm_insecure     = true
  winrm_timeout      = "15m"

  # The combination of using a pre-existing build resource group and this flag
  # ensures a public IP is created for the build VM, making it accessible.
  private_virtual_network_with_public_ip = true

  # This empty plan_info block is a workaround to force a VM provisioning
  # method that does not require creating a temporary Key Vault, which can
  # fail on subscriptions where the Key Vault provider is not registered.
  # This is critical when using an existing build_resource_group_name.
  plan_info {
  }
}

build {
  sources = ["source.azure-arm.autogenerated"]

  provisioner "powershell" {
    inline = [
      "while ((Get-Service -Name \"wuauserv\").Status -ne 'Stopped') { Start-Sleep -s 5 }",
      "while ((Get-Service -Name \"TrustedInstaller\").Status -ne 'Stopped') { Start-Sleep -s 5 }",
      "& $env:SystemRoot\System32\Sysprep\Sysprep.exe /generalize /oobe /shutdown /quiet"
    ]
  }
}