# Configure the AWS Provider
# The region is extracted from the provided JSON configuration (platform.region: us-east-1)
provider "aws" {
  region = "us-east-1"
}

# Generate a new SSH private key using the tls_private_key resource.
# This key will be used to create an AWS Key Pair, allowing secure SSH access to the VM.
# CRITICAL: The 'tls_private_key' resource does not support a 'comment' argument, and it is explicitly forbidden.
resource "tls_private_key" "admin_ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# Create an AWS Key Pair resource using the public key generated by tls_private_key.admin_ssh.
# The key_name is made unique using a random suffix to prevent naming conflicts.
resource "aws_key_pair" "admin_key" {
  key_name   = "admin_ssh_key-${random_id.suffix.hex}"
  public_key = tls_private_key.admin_ssh.public_key_openssh
}

# Data source to find the custom AMI ID.
# This uses the specific image name 'ubuntu-20-04-19182851935' as per the critical instructions.
# It filters by the 'name' tag, looks for AMIs owned by the current account ('self'),
# and retrieves the most recent matching AMI.
data "aws_ami" "this_ami" {
  most_recent = true
  owners      = ["self"]

  filter {
    name   = "name"
    values = ["ubuntu-20-04-19182851935"]
  }
}

# Create a security group to allow inbound SSH traffic (port 22).
# For demonstration purposes, SSH access is allowed from any IP address (0.0.0.0/0).
# All outbound traffic is allowed by default.
resource "aws_security_group" "allow_ssh" {
  name        = "ssh_access_for_vm-${random_id.suffix.hex}"
  description = "Allow SSH inbound traffic to the VM"

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"] # WARNING: In production, restrict this to known IPs.
  }

  # Allow all outbound traffic
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "ssh-sg-${random_id.suffix.hex}"
  }
}

# Deploy the virtual machine.
# CRITICAL: The primary compute resource MUST be named "this_vm".
resource "aws_instance" "this_vm" {
  ami           = data.aws_ami.this_ami.id # Uses the custom AMI found by the data source.
  instance_type = "t3.small"                # Extracted from JSON (platform.vmSize: t3.small).
  key_name      = aws_key_pair.admin_key.key_name # Attaches the generated SSH key pair.

  # Associate the created security group for SSH access.
  vpc_security_group_ids = [aws_security_group.allow_ssh.id]

  # Instance tags, including the Name from the JSON configuration (platform.instanceName: test-tenant-5).
  tags = {
    Name = "test-tenant-5"
  }
  # The 'customScript' from the JSON is explicitly noted as "not yet supported for direct deployment".
  # Therefore, 'user_data' is omitted from the aws_instance resource.
}

# Output the private IP address of the deployed virtual machine.
# CRITICAL: This output MUST be named "private_ip".
output "private_ip" {
  description = "The private IP address of the deployed virtual machine."
  value       = aws_instance.this_vm.private_ip
}

# Output the generated private SSH key.
# CRITICAL: This output MUST be named "private_ssh_key" and MUST be marked as sensitive.
output "private_ssh_key" {
  description = "The private SSH key used to access the virtual machine. Keep this secure!"
  value       = tls_private_key.admin_ssh.private_key_pem
  sensitive   = true # Marks the output as sensitive, preventing it from being shown in plain text in logs.
}

# A random suffix generator to ensure unique names for resources like key pairs and security groups.
resource "random_id" "suffix" {
  byte_length = 8
}