
- hosts: all
  become: yes
  tasks:
    - name: Install Nginx (Debian/Ubuntu)
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Nginx (RHEL/CentOS/Fedora)
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
